# Generated by Django 5.1.1 on 2024-10-08 03:28

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('discord', 'Discord'), ('ambivis', 'Ambivis'), ('shodan', 'Shodan'), ('nist', 'NIST')], max_length=50)),
                ('cred_type', models.CharField(choices=[('password', 'Password'), ('secret', 'Secret'), ('token', 'Token'), ('key', 'Key')], max_length=50)),
                ('value', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
