# Generated by Django 5.1.1 on 2024-10-08 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('source_identifier', models.CharField(max_length=100)),
                ('published', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('vuln_status', models.CharField(max_length=50)),
                ('cisa_exploit_add', models.DateField(blank=True, null=True)),
                ('cisa_action_due', models.DateField(blank=True, null=True)),
                ('cisa_required_action', models.TextField(blank=True, null=True)),
                ('cisa_vulnerability_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'CVE Records',
            },
        ),
        migrations.CreateModel(
            name='CWE',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('abstraction', models.CharField(blank=True, max_length=50, null=True)),
                ('structure', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=50)),
                ('diagram', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(verbose_name=500)),
                ('likelihood_of_exploit', models.CharField(blank=True, max_length=50, null=True)),
                ('cwe_type', models.CharField(choices=[('weakness', 'Weakness'), ('category', 'Category'), ('view', 'View')])),
                ('scope', models.CharField(blank=True, max_length=255, null=True)),
                ('impact', models.CharField(blank=True, max_length=355, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'CWEs',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Priorities',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=10)),
                ('negate', models.BooleanField()),
                ('criteria', models.CharField(max_length=255)),
                ('version_end_excluding', models.CharField(blank=True, max_length=50, null=True)),
                ('version_end_including', models.CharField(blank=True, max_length=50, null=True)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='biotremor.cve')),
            ],
        ),
        migrations.CreateModel(
            name='CVEChange',
            fields=[
                ('event_name', models.CharField(max_length=100)),
                ('cve_change_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('source_identifier', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='biotremor.cve')),
            ],
            options={
                'verbose_name_plural': 'CVE Changes',
            },
        ),
        migrations.CreateModel(
            name='ChangeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('cve_change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='biotremor.cvechange')),
            ],
        ),
        migrations.CreateModel(
            name='CVSSMetricV20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('vector_string', models.CharField(max_length=100)),
                ('access_vector', models.CharField(max_length=50)),
                ('access_complexity', models.CharField(max_length=50)),
                ('authentication', models.CharField(max_length=50)),
                ('confidentiality_impact', models.CharField(max_length=50)),
                ('integrity_impact', models.CharField(max_length=50)),
                ('availability_impact', models.CharField(max_length=50)),
                ('base_score', models.FloatField()),
                ('severity', models.CharField(max_length=50)),
                ('exploitability_score', models.FloatField()),
                ('impact_score', models.FloatField()),
                ('cve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cvss_metrics_v2', to='biotremor.cve')),
            ],
            options={
                'verbose_name_plural': 'CVSS 2.0 Metrics',
            },
        ),
        migrations.CreateModel(
            name='CVSSMetricV31',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('vector_string', models.CharField(max_length=100)),
                ('attack_vector', models.CharField(max_length=50)),
                ('attack_complexity', models.CharField(max_length=50)),
                ('privileges_required', models.CharField(max_length=50)),
                ('user_interaction', models.CharField(max_length=50)),
                ('scope', models.CharField(max_length=50)),
                ('confidentiality_impact', models.CharField(max_length=50)),
                ('integrity_impact', models.CharField(max_length=50)),
                ('availability_impact', models.CharField(max_length=50)),
                ('base_score', models.FloatField()),
                ('base_severity', models.CharField(max_length=50)),
                ('exploitability_score', models.FloatField()),
                ('impact_score', models.FloatField()),
                ('cve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cvss_metrics_v3', to='biotremor.cve')),
            ],
            options={
                'verbose_name_plural': 'CVSS 3.1 Metrics',
            },
        ),
        migrations.CreateModel(
            name='EPSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('percentile', models.FloatField()),
                ('date', models.DateField()),
                ('cve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='epss', to='biotremor.cve')),
            ],
            options={
                'verbose_name_plural': 'EPSS Metrics',
            },
        ),
        migrations.CreateModel(
            name='PreProcessedCVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cisa_exploit_add', models.IntegerField(choices=[(0, 'False'), (1, 'True')])),
                ('cve_published_epoch', models.IntegerField(blank=True, null=True)),
                ('weakness_cwe_encoded', models.IntegerField()),
                ('cvss_v31_base_score', models.FloatField()),
                ('cvss_v31_exploitability_score', models.FloatField()),
                ('cvss_v31_impact_score', models.FloatField()),
                ('cvss_v31_attack_vector_encoded', models.IntegerField()),
                ('cvss_v31_attack_complexity_encoded', models.IntegerField()),
                ('cvss_v31_privileges_required_encoded', models.IntegerField()),
                ('cvss_v31_user_interaction_encoded', models.IntegerField()),
                ('cvss_v31_scope_encoded', models.IntegerField()),
                ('cvss_v31_confidentiality_impact_encoded', models.IntegerField()),
                ('cvss_v31_integrity_impact_encoded', models.IntegerField()),
                ('cvss_v31_availability_impact_encoded', models.IntegerField()),
                ('cvss_v20_base_score', models.FloatField()),
                ('cvss_v20_exploitability_score', models.FloatField()),
                ('cvss_v20_impact_score', models.FloatField()),
                ('cvss_v20_access_vector_encoded', models.IntegerField()),
                ('cvss_v20_access_complexity_encoded', models.IntegerField()),
                ('cvss_v20_authentication_encoded', models.IntegerField()),
                ('cvss_v20_confidentiality_impact_encoded', models.IntegerField()),
                ('cvss_v20_integrity_impact_encoded', models.IntegerField()),
                ('cvss_v20_availability_impact_encoded', models.IntegerField()),
                ('epss_score', models.FloatField()),
                ('epss_percentile', models.FloatField()),
                ('has_patch', models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=0)),
                ('has_mitigation', models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=0)),
                ('has_us_gov_resource', models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=0)),
                ('has_press_media_coverage', models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=0)),
                ('has_exploit', models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=0)),
                ('cve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biotremor.cve')),
                ('rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biotremor.priority')),
            ],
            options={
                'verbose_name_plural': 'Pre-Processed CVEs',
            },
        ),
        migrations.CreateModel(
            name='CVERating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], max_length=6)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=255)),
                ('cve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biotremor.cve')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biotremor.priority')),
            ],
            options={
                'verbose_name_plural': 'CVE Ratings',
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('value', models.TextField()),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='biotremor.cve')),
            ],
            options={
                'unique_together': {('cve', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=400)),
                ('source', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=255)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='biotremor.cve')),
            ],
            options={
                'unique_together': {('cve', 'url')},
            },
        ),
        migrations.CreateModel(
            name='Weakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to='biotremor.cve')),
                ('cwe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weaknesses', to='biotremor.cwe')),
            ],
            options={
                'unique_together': {('cve', 'cwe')},
            },
        ),
    ]
