# Generated by Django 5.1.1 on 2024-10-08 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambivis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RSSFilter',
        ),
    ]
